### ISSUE TITLE
App crashes immediatelly on Samsung Galaxy Tab A7 SM-T500

### ISSUE THREAD

**Issue by xisberto** [damionx7/Zettel-Notes-Documentation#5]
Hi. I'm using the app installed by your F-Droid repository on a Motorola phone without problems.

But on my tablet the app crashes just after start.

The installed version is 1.0.80.

Bellow follows the logcat.

```
2023-01-09 17:43:40.672   788-788   Zygote                  pid-788                              D  Forked child process 23577
2023-01-09 17:43:40.672  1245-1792  ActivityManager         pid-1245                             I  Start proc 23577:org.eu.thedoc.zettelnotes/u0a387 for activelaunch {org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.splash.SplashActivity}
2023-01-09 17:43:40.702 23577-23577 doc.zettelnote          pid-23577                            E  Not starting debugger since process cannot load the jdwp agent.
2023-01-09 17:43:40.708 23577-23577 USNET                   pid-23577                            E  USNET: appName: org.eu.thedoc.zettelnotes
2023-01-09 17:43:40.709 23577-23577 ProcessState            pid-23577                            D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2023-01-09 17:43:40.718 23577-23577 ActivityThread          pid-23577                            D  setConscryptValidator
2023-01-09 17:43:40.718 23577-23577 ActivityThread          pid-23577                            D  setConscryptValidator - put
2023-01-09 17:43:40.808  1245-2044  ActivityManager         pid-1245                             D  attachApplicationLocked() app=ProcessRecord{8b51790 23577:org.eu.thedoc.zettelnotes/u0a387} app.isolatedEntryPoint=null instr2=null
2023-01-09 17:43:40.831  1245-1969  ActivityManager         pid-1245                             V  Changed top to ProcessRecord{8b51790 23577:org.eu.thedoc.zettelnotes/u0a387}
2023-01-09 17:43:40.832 23577-23577 ActivityThread          pid-23577                            D  handleBindApplication()++ app=org.eu.thedoc.zettelnotes
2023-01-09 17:43:40.833 23577-23577 Compatibil...geReporter pid-23577                            D  Compat change id reported: 171979766; UID 10387; state: ENABLED
2023-01-09 17:43:40.862 23577-23577 GraphicsEnvironment     pid-23577                            V  ANGLE Developer option for 'org.eu.thedoc.zettelnotes' set to: 'default'
2023-01-09 17:43:40.862 23577-23577 GraphicsEnvironment     pid-23577                            V  Neither updatable production driver nor prerelease driver is supported.
2023-01-09 17:43:40.864 23577-23577 LoadedApk               pid-23577                            D  LoadedApk::makeApplication() appContext.mOpPackageName=org.eu.thedoc.zettelnotes appContext.mBasePackageName=org.eu.thedoc.zettelnotes
2023-01-09 17:43:40.865 23577-23577 NetworkSecurityConfig   pid-23577                            D  Using Network Security Config from resource network_security_config debugBuild: false
2023-01-09 17:43:40.870 23577-23577 NetworkSecurityConfig   pid-23577                            D  Using Network Security Config from resource network_security_config debugBuild: false
2023-01-09 17:43:40.873 23577-23577 MultiDex                pid-23577                            I  VM with version 2.1.0 has multidex support
2023-01-09 17:43:40.873 23577-23577 MultiDex                pid-23577                            I  Installing application
2023-01-09 17:43:40.873 23577-23577 MultiDex                pid-23577                            I  VM has multidex support, MultiDex support library is disabled.
2023-01-09 17:43:40.880 23577-23577 WM-WrkMgrInitializer    pid-23577                            D  Initializing WorkManager with default configuration.
2023-01-09 17:43:40.885 23577-23577 doc.zettelnote          pid-23577                            W  Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
2023-01-09 17:43:40.885 23577-23577 doc.zettelnote          pid-23577                            W  Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2023-01-09 17:43:40.885 23577-23577 doc.zettelnote          pid-23577                            W  Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
2023-01-09 17:43:40.900 23577-23577 ActivityThread          pid-23577                            D  handleBindApplication() --
2023-01-09 17:43:40.919 23577-23601 Compatibil...geReporter pid-23577                            D  Compat change id reported: 160794467; UID 10387; state: ENABLED
2023-01-09 17:43:40.960 23577-23603 OpenGLRenderer          pid-23577                            D  RenderThread::requireGlContext()
2023-01-09 17:43:40.961 23577-23603 AdrenoGLES-0            pid-23577                            I  QUALCOMM build                   : 5eaa426211, I07ee46fc66
                                                                                                    Build Date                       : 10/08/21
                                                                                                    OpenGL ES Shader Compiler Version: EV031.32.02.16
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-01-09 17:43:40.961 23577-23603 AdrenoGLES-0            pid-23577                            I  Build Config                     : S P 10.0.7 AArch64
2023-01-09 17:43:40.961 23577-23603 AdrenoGLES-0            pid-23577                            I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-01-09 17:43:40.967 23577-23603 AdrenoGLES-0            pid-23577                            I  PFP: 0x016ee197, ME: 0x00000000
2023-01-09 17:43:40.989 23577-23603 OpenGLRenderer          pid-23577                            D  RenderThread::setGrContext()
2023-01-09 17:43:41.007  1245-9661  ActivityTaskManager     pid-1245                             D  startActivityAsUser: callingPid=23577, callingUid=10387, caller=com.android.server.wm.ActivityTaskManagerService.startActivityAsUser:1744 com.android.server.wm.ActivityTaskManagerService.startActivity:1697 android.app.IActivityTaskManager$Stub.onTransact:1132 com.android.server.wm.ActivityTaskManagerService.onTransact:6223 android.os.Binder.execTransactInternal:1215 android.os.Binder.execTransact:1179 <bottom of call stack> 
2023-01-09 17:43:41.061 23577-23577 DecorView               pid-23577                            I  [INFO] isPopOver=false, config=true
2023-01-09 17:43:41.061 23577-23577 DecorView               pid-23577                            I  updateCaptionType >> DecorView@bea16fc[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
2023-01-09 17:43:41.061 23577-23577 DecorView               pid-23577                            D  setCaptionType = 0, this = DecorView@bea16fc[]
2023-01-09 17:43:41.065 23577-23577 DecorView               pid-23577                            I  getCurrentDensityDpi: from real metrics. densityDpi=240 msg=resources_loaded
2023-01-09 17:43:41.103 23577-23577 Dialog                  pid-23577                            I  mIsDeviceDefault = false, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
2023-01-09 17:43:41.239 23577-23577 Compatibil...geReporter pid-23577                            D  Compat change id reported: 171228096; UID 10387; state: ENABLED
2023-01-09 17:43:41.261 23577-23577 DecorView               pid-23577                            I  [INFO] isPopOver=false, config=true
2023-01-09 17:43:41.261 23577-23577 DecorView               pid-23577                            I  updateCaptionType >> DecorView@7ee713d[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
2023-01-09 17:43:41.261 23577-23577 DecorView               pid-23577                            D  setCaptionType = 0, this = DecorView@7ee713d[]
2023-01-09 17:43:41.261 23577-23577 DecorView               pid-23577                            I  getCurrentDensityDpi: from real metrics. densityDpi=240 msg=resources_loaded
2023-01-09 17:43:41.299 23577-23577 ViewRootIm...nActivity] pid-23577                            I  setView = com.android.internal.policy.DecorView@7ee713d TM=true
2023-01-09 17:43:41.312 23577-23577 IMM_LC                  pid-23577                            I  hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1858 android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1827 androidx.appcompat.widget.SearchView$SearchAutoComplete.setImeVisibility:26 androidx.appcompat.widget.SearchView.clearFocus:14 androidx.appcompat.widget.SearchView.onCloseClicked:27 
2023-01-09 17:43:41.312 23577-23577 IMM_LC                  pid-23577                            I  hsifw() ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView :0
2023-01-09 17:43:41.329 23577-23577 error                   pid-23577                            E  Error creating account
2023-01-09 17:43:41.346 23577-23577 TextToSpeech            pid-23577                            I  Sucessfully bound to com.samsung.SMT
2023-01-09 17:43:41.364  1028-2023  SurfaceFlinger          pid-1028                             I  id=9761 createSurf (1x1),-3 flag=40004, org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577#0
2023-01-09 17:43:41.365  1245-9369  WindowManager           pid-1245                             D  makeSurface duration=1 name=org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577
2023-01-09 17:43:41.373  1245-9369  WindowManager           pid-1245                             V  Relayout hash=d7a2581, pid=23577: mAttrs={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030303
                                                                                                      fl=81810100
                                                                                                      pfl=12020040
                                                                                                      bhv=DEFAULT
                                                                                                      fitSides= naviIconColor=0}
2023-01-09 17:43:41.376 23577-23577 ViewRootIm...nActivity] pid-23577                            I  Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)0 dur=12 res=0x7 s={true -5476376628203679744} ch=true fn=-1
2023-01-09 17:43:41.379 23577-23603 hw-ProcessState         pid-23577                            D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2023-01-09 17:43:41.379 23577-23603 OpenGLRenderer          pid-23577                            D  eglCreateWindowSurface
2023-01-09 17:43:41.431 23577-23577 AbsListView             pid-23577                            D   in onLayout changed 
2023-01-09 17:43:41.434 23577-23577 ViewRootIm...nActivity] pid-23577                            I  [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
2023-01-09 17:43:41.438 23577-23577 ViewRootIm...nActivity] pid-23577                            D  Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023-01-09 17:43:41.438 23577-23577 ViewRootIm...nActivity] pid-23577                            D  Creating frameCompleteCallback
2023-01-09 17:43:41.444 23577-23641 ViewRootIm...nActivity] pid-23577                            D  Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
2023-01-09 17:43:41.495 23577-23603 ViewRootIm...nActivity] pid-23577                            D  Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
2023-01-09 17:43:41.498 23577-23577 ViewRootIm...nActivity] pid-23577                            I  [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2023-01-09 17:43:41.498 23577-23577 ViewRootIm...nActivity] pid-23577                            I  [DP] rdf()
2023-01-09 17:43:41.498 23577-23577 ViewRootIm...nActivity] pid-23577                            D  reportDrawFinished (fn: -1) 
2023-01-09 17:43:41.528  1028-1028  SurfaceFlinger          pid-1028                             D  Display 4630946442617851009 HWC layers:
                                                                                                         DEVICE | 0xb400007a647f2720 | 0102 | RGBA_8888    |    0.0    0.0 1200.0 2000.0 |    0    0 1200 2000 | org.eu.thedoc.zettelnotes/org.eu.the[...]ns.common.main.MainActivity$_23577#0
                                                                                                         CLIENT | 0xb400007a647f2090 | 0100 | RGBA_8888    |    0.0    0.0 1200.0 2000.0 |    0    0 1200 2000 | Splash Screen org.eu.thedoc.zettelnotes$_9031#0
                                                                                                         CLIENT | 0xb400007a75691450 | 0100 | RGBA_8888    |    0.0    0.0   36.0 2000.0 | 1164    0 1200 2000 | StatusBar$_9031#0
                                                                                                         CLIENT | 0xb400007a647efcb0 | 0100 | RGBA_8888    |    0.0    0.0  106.0   67.0 |  747 1933  853 2000 | com.samsung.android.app.cocktailbars[...]rservice.CocktailBarService$_11317#0
                                                                                                         CLIENT | 0xb400007a75692020 | 0100 | RGBA_8888    |    0.0    0.0   72.0 2000.0 |    0    0   72 2000 | NavigationBar0$_9031#0
2023-01-09 17:43:41.692 23577-23592 TextToSpeech            pid-23577                            I  Connected to TTS engine
2023-01-09 17:43:41.695  1028-1028  SurfaceFlinger          pid-1028                             D  Display 4630946442617851009 HWC layers:
                                                                                                         DEVICE | 0xb400007a647f2720 | 0102 | RGBA_8888    |    0.0    0.0 1200.0 2000.0 |    0    0 1200 2000 | org.eu.thedoc.zettelnotes/org.eu.the[...]ns.common.main.MainActivity$_23577#0
                                                                                                         DEVICE | 0xb400007a75691450 | 0100 | RGBA_8888    |    0.0    0.0   36.0 2000.0 | 1164    0 1200 2000 | StatusBar$_9031#0
                                                                                                         CLIENT | 0xb400007a647efcb0 | 0100 | RGBA_8888    |    0.0    0.0  106.0   67.0 |  747 1933  853 2000 | com.samsung.android.app.cocktailbars[...]rservice.CocktailBarService$_11317#0
                                                                                                         CLIENT | 0xb400007a75692020 | 0100 | RGBA_8888    |    0.0    0.0   72.0 2000.0 |    0    0   72 2000 | NavigationBar0$_9031#0
2023-01-09 17:43:41.696 23577-23658 TextToSpeech            pid-23577                            I  Setting up the connection to TTS engine...
2023-01-09 17:43:41.738 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  setView = android.widget.PopupWindow$PopupDecorView@aec390c TM=true
2023-01-09 17:43:41.851  1028-2023  SurfaceFlinger          pid-1028                             I  id=9767 createSurf (1x1),-3 flag=40004, PopupWindow:f950ee0$_23577#0
2023-01-09 17:43:41.851  1245-11323 WindowManager           pid-1245                             D  makeSurface duration=1 name=PopupWindow:f950ee0$_23577
2023-01-09 17:43:41.854 23577-23592 ViewRootIm...w:f950ee0] pid-23577                            I  Resizing android.view.ViewRootImpl@f24eca3: frame=[0,36][0,1177] reportDraw=true forceLayout=false backDropFrame=Rect(0, 0 - 0, 1141)
2023-01-09 17:43:41.856  1245-11323 WindowManager           pid-1245                             V  Relayout hash=4b3febe, pid=23577: mAttrs={(0,0)(0xfill) gr=TOP START CENTER sim={state=always_visible adjust=resize} ty=APPLICATION_PANEL fmt=TRANSPARENT surfaceInsets=Rect(0, 0 - 0, 0) (manual)
                                                                                                      fl=41820008
                                                                                                      pfl=2018000
                                                                                                      bhv=DEFAULT
                                                                                                      fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR IME naviIconColor=0
                                                                                                      sfl=20000}
2023-01-09 17:43:41.858 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  Relayout returned: old=(0,36,2000,1177) new=(0,36,0,1177) req=(0,1141)0 dur=8 res=0x7 s={true -5476376630157053952} ch=true fn=-1
2023-01-09 17:43:41.858 23577-23603 OpenGLRenderer          pid-23577                            D  eglCreateWindowSurface
2023-01-09 17:43:41.859 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
2023-01-09 17:43:41.859 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023-01-09 17:43:41.859 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  Creating frameCompleteCallback
2023-01-09 17:43:41.860 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
2023-01-09 17:43:41.860 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] rdf()
2023-01-09 17:43:41.860 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  reportDrawFinished (fn: -1) 
2023-01-09 17:43:41.860 23577-23577 InsetsSourceConsumer    pid-23577                            D  ensureControlAlpha: for ITYPE_NAVIGATION_BAR on org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity
2023-01-09 17:43:41.861 23577-23577 InsetsSourceConsumer    pid-23577                            D  ensureControlAlpha: for ITYPE_STATUS_BAR on org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity
2023-01-09 17:43:41.869 23577-23577 error                   pid-23577                            E  java.lang.Exception: Language not supported
                                                                                                    	at re.a.onInit(SourceFile:172)
                                                                                                    	at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$TextToSpeech(TextToSpeech.java:890)
                                                                                                    	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda17.run(Unknown Source:4)
                                                                                                    	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
                                                                                                    	at android.speech.tts.TextToSpeech.access$900(TextToSpeech.java:79)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
                                                                                                    	at android.os.AsyncTask.finish(AsyncTask.java:771)
                                                                                                    	at android.os.AsyncTask.access$900(AsyncTask.java:199)
                                                                                                    	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2023-01-09 17:43:41.870 23577-23577 error                   pid-23577                            E  java.lang.Exception: Language not supported
                                                                                                    	at re.a.onInit(SourceFile:172)
                                                                                                    	at android.speech.tts.TextToSpeech.lambda$dispatchOnInit$0$TextToSpeech(TextToSpeech.java:890)
                                                                                                    	at android.speech.tts.TextToSpeech$$ExternalSyntheticLambda17.run(Unknown Source:4)
                                                                                                    	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:899)
                                                                                                    	at android.speech.tts.TextToSpeech.access$900(TextToSpeech.java:79)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2280)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2240)
                                                                                                    	at android.os.AsyncTask.finish(AsyncTask.java:771)
                                                                                                    	at android.os.AsyncTask.access$900(AsyncTask.java:199)
                                                                                                    	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2023-01-09 17:43:41.870 23577-23577 ViewRootIm...nActivity] pid-23577                            I  MSG_WINDOW_FOCUS_CHANGED 1 1
2023-01-09 17:43:41.872 23577-23577 InputMethodManager      pid-23577                            D  startInputInner - Id : 0
2023-01-09 17:43:41.872 23577-23577 InputMethodManager      pid-23577                            I  startInputInner - mService.startInputOrWindowGainedFocus
2023-01-09 17:43:41.873  1245-11323 InputMetho...gerService pid-1245                             V  Creating new session for client ClientState{c20cc35 uid=10387 pid=23577 displayId=0}
2023-01-09 17:43:41.920 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  handleResized, msg = 5 frames=ClientWindowFrames{frame=[0,36][0,1177] display=[0,36][2000,1177] backdrop=[0,0][0,1141]} forceNextWindowRelayout=false displayId=0 frameChanged=false backdropFrameChanged=true configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={0.9 ?mcc?mnc [pt_BR] ldltr sw800dp w1333dp h760dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1177) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} as.19 s.1582 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0} mOverrideConfig={0.9 ?mcc?mnc [pt_BR] ldltr sw800dp w1333dp h760dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1177) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} as.19 s.1 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0}}
2023-01-09 17:43:41.920 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.handleResized:2222 android.view.ViewRootImpl.access$1200:294 
2023-01-09 17:43:41.925 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
2023-01-09 17:43:41.925 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  Creating frameCompleteCallback
2023-01-09 17:43:41.934 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
2023-01-09 17:43:41.934 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            I  [DP] rdf()
2023-01-09 17:43:41.934 23577-23577 ViewRootIm...w:f950ee0] pid-23577                            D  reportDrawFinished (fn: -1) 
2023-01-09 17:43:41.935 23577-23577 AndroidRuntime          pid-23577                            D  Shutting down VM
2023-01-09 17:43:41.936 23577-23577 AndroidRuntime          pid-23577                            E  FATAL EXCEPTION: main
                                                                                                    Process: org.eu.thedoc.zettelnotes, PID: 23577
                                                                                                    java.lang.NullPointerException: Attempt to read from field 'h.s de.a.h' on a null object reference
                                                                                                    	at g8.c.x(SourceFile:5)
                                                                                                    	at h4.d.run(SourceFile:714)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2023-01-09 17:43:41.970 23577-23577 Process                 pid-23577                            I  Sending signal. PID: 23577 SIG: 9
2023-01-09 17:43:42.014   788-788   Zygote                  pid-788                              I  Process 23577 exited due to signal 9 (Killed)
2023-01-09 17:43:42.014  1245-11580 WindowManager           pid-1245                             I  Destroying surface Surface(name=PopupWindow:f950ee0$_23577)/@0x581a82b called by com.android.server.wm.WindowStateAnimator.destroySurface:987 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:518 com.android.server.wm.WindowState.removeImmediately:2960 com.android.server.wm.WindowContainer.removeImmediately:723 com.android.server.wm.WindowState.removeImmediately:2898 com.android.server.wm.WindowState.removeIfPossible:3151 com.android.server.wm.WindowState.access$300:334 com.android.server.wm.WindowState$DeathRecipient.binderDied:3725 
2023-01-09 17:43:42.016  1245-11854 ActivityManager         pid-1245                             I  Process org.eu.thedoc.zettelnotes (pid 23577) has died: prcp TOP (86,591)
2023-01-09 17:43:42.018  1245-1793  libprocessgroup         pid-1245                             I  Successfully killed process cgroup uid 10387 pid 23577 in 0ms
2023-01-09 17:43:42.028  1245-11580 WindowManager           pid-1245                             I  Destroying surface Surface(name=org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577)/@0xe6c134 called by com.android.server.wm.WindowStateAnimator.destroySurface:987 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:518 com.android.server.wm.WindowState.removeImmediately:2960 com.android.server.wm.WindowState.removeIfPossible:3151 com.android.server.wm.WindowState.access$300:334 com.android.server.wm.WindowState$DeathRecipient.binderDied:3725 android.os.IBinder$DeathRecipient.binderDied:320 android.os.BinderProxy.sendDeathNotice:750 
2023-01-09 17:43:42.032  1028-1028  Layer                   pid-1028                             I  id=9767 mRemovedFromDrawingState PopupWindow:f950ee0$_23577#0 (125)
2023-01-09 17:43:42.032  1028-1028  Layer                   pid-1028                             I  id=9761 mRemovedFromDrawingState org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577#0 (125)
2023-01-09 17:43:42.032  1028-1028  SurfaceFlinger          pid-1028                             I  id=9761 Removed org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577#0 (125)
2023-01-09 17:43:42.033  1028-1028  SurfaceFlinger          pid-1028                             I  id=9767 Removed PopupWindow:f950ee0$_23577#0 (125)
2023-01-09 17:43:42.033  1028-1028  Layer                   pid-1028                             I  id=9767 Destroyed PopupWindow:f950ee0$_23577#0
2023-01-09 17:43:42.036  1028-1028  Layer                   pid-1028                             I  id=9761 Destroyed org.eu.thedoc.zettelnotes/org.eu.thedoc.zettelnotes.screens.common.main.MainActivity$_23577#0
2023-01-09 17:43:42.039  1245-11579 WindowManager           pid-1245                             W  Failed looking up window session=Session{3c8ce5a 23577:u0a10387} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6297 com.android.server.wm.WindowState$DeathRecipient.binderDied:3718 android.os.IBinder$DeathRecipient.binderDied:320 
2023-01-09 17:43:42.141  1245-1772  ActivityManager         pid-1245                             W  setHasOverlayUi called on unknown pid: 23577
2023-01-09 17:43:42.813   991-1091  ANDR-PERF-UTIL          pid-991                              E  Failed to update node /proc/23577/sched_boost with value 0
2023-01-09 17:43:42.813   991-1091  ANDR-PERF-OPTSHANDLER   pid-991                              E  can't reset task 23577
```

**Comment by damionx7** [comment]
I will look into the issue.

**Comment by damionx7** [comment]
@xisberto Can you explain the context in which this error occured ?

**Comment by xisberto** [comment]
There wasn't really any context, I installed the app from F-Droid, opened it and it closed by itself.

After these week's update, I tried again and it worked.
